version: "3.2"

services:

  db:
    container_name: dbcompiler
    image: postgres:14.1
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbcompiler
      - POSTGRES_PASSWORD=dbcompiler
      - POSTGRES_DB=dbcompiler
    ports:
      - "5432:5432"

  rmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  javascript:
    build: ./javascript
    image: javascript/latest

  python:
    build: ./python
    image: python:latest

  app:
    build: .
    networks:
      - my-network

  consumer:
    build: ./rabbitMQ
    container_name: rabbitmq_consumer
    depends_on:
      - rmq
      - db
    networks:
      - my-network

  
volumes: 
  postgresql-volume:
    external: true

networks:
  my-network:
    driver: bridge