version: "3.2"

services:
  db:
    container_name: dbcompiler
    image: postgres:14.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbcompiler
      - POSTGRES_PASSWORD=dbcompiler
      - POSTGRES_DB=dbcompiler
    ports:
      - "5432:5432"
    hostname: dbcompiler
    networks:
      - my-network

  amqp:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    networks:
      - my-network
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    image: server-consumer
    restart: always
    networks:
      - my-network
    ports:
      - 8000:8000
    depends_on:
      - amqp
      - db

# volumes:
#   postgresql-volume:
#     external: true

networks:
  my-network:
    driver: bridge
